# Copyright 2026 -- CONTRIBUTORS. See LICENSE.

load("@lib//bazel:copts.bzl", "COPTS")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "units",
    hdrs = ["units.hpp"],
    copts = COPTS,
    deps = [
        "//framework:vocabulary",
        "@eigen",
        "@mp-units",
    ],
)

cc_test(
    name = "units_test",
    size = "small",
    srcs = ["units_test.cpp"],
    copts = COPTS,
    deps = [
        ":units",
        "@lib//base:testing",
    ],
)

cc_library(
    name = "kinematics",
    hdrs = ["kinematics.hpp"],
    copts = COPTS,
    deps = [
        "//framework:vocabulary",
        ":units",
        "//framework",
        "@eigen",
        "@lib//base:core",
    ],
)

cc_library(
    name = "motion",
    hdrs = ["motion.hpp"],
    copts = COPTS,
    deps = [
        "//framework:vocabulary",
        ":kinematics",
        "//framework",
    ],
)

cc_test(
    name = "kinematics_test",
    size = "small",
    srcs = ["kinematics_test.cpp"],
    copts = COPTS,
    deps = [
        "//framework:vocabulary",
        ":kinematics",
        "@lib//base:testing",
    ],
)

cc_library(
    name = "guidance",
    hdrs = ["guidance.hpp"],
    copts = COPTS,
    deps = [
        ":kinematics",
        ":units",
    ],
)

cc_library(
    name = "atmosphere",
    hdrs = ["atmosphere.hpp"],
    copts = COPTS,
    deps = [":units"],
)

cc_library(
    name = "control",
    hdrs = ["control.hpp"],
    copts = COPTS,
    deps = [
        "//framework:vocabulary",
        ":units",
        "@lib//base:core",
    ],
)

cc_library(
    name = "aerodynamics",
    srcs = ["aerodynamics.cpp"],
    hdrs = ["aerodynamics.hpp"],
    copts = COPTS,
    deps = [
        ":control",
        ":units",
    ],
)

cc_library(
    name = "flight_control",
    srcs = ["flight_control.cpp"],
    hdrs = ["flight_control.hpp"],
    copts = COPTS,
    deps = [
        ":control",
        ":units",
    ],
)

cc_library(
    name = "aircraft_data",
    srcs = ["aircraft_data.cpp"],
    hdrs = ["aircraft_data.hpp"],
    copts = COPTS,
    deps = [
        ":aerodynamics",
        ":flight_control",
        ":units",
        "@lib//base:status",
    ],
)

cc_library(
    name = "earth",
    hdrs = ["earth.hpp"],
    copts = COPTS,
    deps = [
        ":units",
        "@eigen",
    ],
)

cc_library(
    name = "rigid_body",
    hdrs = ["rigid_body.hpp"],
    copts = COPTS,
    deps = [
        ":kinematics",
        ":units",
        "//framework",
        "@eigen",
    ],
)

cc_library(
    name = "turbine",
    srcs = ["turbine.cpp"],
    hdrs = ["turbine.hpp"],
    copts = COPTS,
    deps = [
        ":aerodynamics",
        ":aircraft_data",
        ":units",
    ],
)

cc_library(
    name = "rigid_aircraft",
    srcs = ["rigid_aircraft.cpp"],
    hdrs = ["rigid_aircraft.hpp"],
    copts = COPTS,
    deps = [
        ":aerodynamics",
        ":aircraft_data",
        ":atmosphere",
        ":earth",
        ":flight_path",
        ":rigid_body",
        ":turbine",
        ":units",
        ":wind",
        "@eigen",
        "@lib//base:core",
    ],
)

cc_test(
    name = "rigid_aircraft_test",
    size = "small",
    srcs = ["rigid_aircraft_test.cpp"],
    copts = COPTS,
    deps = [
        ":rigid_aircraft",
        "@lib//base:testing",
    ],
)

cc_library(
    name = "trim",
    srcs = ["trim.cpp"],
    hdrs = ["trim.hpp"],
    copts = COPTS,
    deps = [
        ":aircraft_data",
        ":atmosphere",
        ":flight_control",
        ":rigid_aircraft",
        ":rigid_body",
        ":units",
        "@eigen",
        "@lib//base:core",
        "@lib//base:status",
    ],
)

cc_test(
    name = "rigid_body_test",
    size = "small",
    srcs = ["rigid_body_test.cpp"],
    copts = COPTS,
    deps = [
        ":rigid_body",
        "//framework:continuous",
        "@lib//base:testing",
    ],
)

cc_library(
    name = "flight_path",
    hdrs = ["flight_path.hpp"],
    copts = COPTS,
    deps = [
        ":atmosphere",
        ":kinematics",
        ":units",
        "//framework",
        "@eigen",
    ],
)

cc_library(
    name = "wind",
    srcs = ["wind.cpp"],
    hdrs = ["wind.hpp"],
    copts = COPTS,
    deps = [
        ":units",
        "//framework:vocabulary",
        "@eigen",
    ],
)

cc_library(
    name = "random",
    hdrs = ["random.hpp"],
    copts = COPTS,
)

[cc_test(
    name = test + "_test",
    size = "small",
    srcs = [test + "_test.cpp"],
    copts = COPTS,
    deps = [
        ":" + test,
        "@lib//base:testing",
    ],
) for test in [
    "aerodynamics",
    "aircraft_data",
    "atmosphere",
    "earth",
    "control",
    "flight_path",
    "guidance",
    "random",
    "wind",
]]
