# Copyright 2026 -- CONTRIBUTORS. See LICENSE.

load("@lib//bazel:copts.bzl", "COPTS")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "viewing",
    hdrs = ["viewing.hpp"],
    copts = COPTS,
    deps = [
        "//engine:driver",
        "//core:vocabulary",
        "//3rd_party:imgui",
        "//3rd_party:imgui_platform_sdl2",
        "//3rd_party:imgui_renderer_sdl2",
        "//3rd_party:implot",
        "//3rd_party:sdl2",
    ],
)

cc_library(
    name = "testing",
    testonly = True,
    hdrs = ["testing.hpp"],
    copts = COPTS,
    deps = ["@lib//base:testing"],
)
