# Copyright 2026 -- CONTRIBUTORS. See LICENSE.

load("@lib//bazel:copts.bzl", "COPTS")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "aircraft_file",
    srcs = ["aircraft_file.cpp"],
    hdrs = ["aircraft_file.hpp"],
    copts = COPTS,
    deps = [
        "//model:aircraft_data",
        "@lib//base:core",
        "@lib//base:status",
    ],
)

cc_library(
    name = "opendrive",
    srcs = ["opendrive.cpp"],
    hdrs = ["opendrive.hpp"],
    copts = COPTS,
    deps = [
        "//framework:vocabulary",
        "//model:road",
        "@lib//base:core",
        "@lib//base:status",
        "@pugixml",
    ],
)

cc_library(
    name = "openscenario",
    srcs = ["openscenario.cpp"],
    hdrs = ["openscenario.hpp"],
    copts = COPTS,
    deps = [
        "//scenario:openscenario",
        "@lib//base:core",
        "@lib//base:status",
        "@pugixml",
    ],
)

cc_library(
    name = "tire_file",
    srcs = ["tire_file.cpp"],
    hdrs = ["tire_file.hpp"],
    copts = COPTS,
    deps = [
        "//model:tire",
        "@lib//base:core",
        "@lib//base:status",
    ],
)

[cc_test(
    name = test + "_test",
    size = "small",
    srcs = [test + "_test.cpp"],
    copts = COPTS,
    deps = [
        ":" + test,
        "@lib//base:testing",
    ],
) for test in [
    "aircraft_file",
    "opendrive",
]]
