# Copyright 2026 -- CONTRIBUTORS. See LICENSE.

load("@lib//bazel:copts.bzl", "COPTS")
load("//application:viewer.bzl", "application_viewer")
load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "hello_library",
    srcs = ["hello.cpp"],
    hdrs = ["hello.hpp"],
    copts = COPTS,
    deps = [
        "//core:argument",
        "//framework",
        "//engine:lifecycle",
        "//model:kinematics",
        "//core:random",
        "//core:units",
    ],
)

cc_test(
    name = "hello_test",
    size = "small",
    srcs = ["hello_test.cpp"],
    copts = COPTS,
    deps = [
        "//core:argument",
        ":hello_library",
        "//engine:driver",
        "@lib//base:testing",
    ],
)

cc_binary(
    name = "hello",
    srcs = ["main.cpp"],
    copts = COPTS,
    deps = [
        "//core:argument",
        ":hello_library",
        "//engine:driver",
    ],
)

application_viewer(
    deps = [
        "//core:argument",
        ":hello_library",
        "//application:viewing",
        "//engine:driver",
        "//3rd_party:imgui",
        "//3rd_party:implot",
        "@lib//base:core",
    ],
    tests = {
        "viewer_test": ["--frames=60"],
    },
)

