# Copyright 2022 -- CONTRIBUTORS. See LICENSE.

load("@lib//bazel:copts.bzl", "COPTS")
load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "hello_library",
    hdrs = ["hello.hpp"],
    copts = COPTS,
    deps = [
        "//framework",
        "//engine:lifecycle",
        "//model:kinematics",
        "//model:motion",
        "//model:units",
    ],
)

cc_test(
    name = "hello_test",
    size = "small",
    srcs = ["hello_test.cpp"],
    copts = COPTS,
    deps = [
        ":hello_library",
        "//engine:driver",
        "@lib//base:testing",
    ],
)

cc_binary(
    name = "hello",
    srcs = ["main.cpp"],
    copts = COPTS,
    deps = [
        ":hello_library",
        "//engine:driver",
        "@imgui",
        "@imgui//backends:platform-sdl2",
        "@imgui//backends:renderer-sdl2",
        "@sdl2",
    ],
)
