# Copyright 2026 -- CONTRIBUTORS. See LICENSE.

load("@lib//bazel:copts.bzl", "COPTS")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_test(
    name = "model_test",
    size = "small",
    srcs = ["model_test.cpp"],
    copts = COPTS,
    data = glob(["models/*.xml"]) + [
        "reference/mujoco_models.csv",
        "//3rd_party:mujoco",
    ],
    deps = [
        "//format:mjcf",
        "//model:articulated",
        "@lib//base:testing",
    ],
)

cc_library(
    name = "robotic_library",
    srcs = [
        "simulation.cpp",
        "simulation_systems.cpp",
    ],
    hdrs = [
        "simulation.hpp",
        "simulation_components.hpp",
        "simulation_systems.hpp",
    ],
    copts = COPTS,
    deps = [
        "//engine:lifecycle",
        "//format:mjcf",
        "//framework",
        "//framework:vocabulary",
        "//model:articulated",
        "//model:articulated_collision",
        "//model:articulated_constraint",
        "//model:articulated_dynamics",
        "//model:kinematics",
        "//model:units",
    ],
)

cc_test(
    name = "dynamics_test",
    size = "small",
    srcs = ["dynamics_test.cpp"],
    copts = COPTS,
    data = glob(["models/*.xml"]) + ["reference/mujoco_dynamics.csv"],
    deps = [
        ":robotic_library",
        "@lib//base:testing",
    ],
)

cc_test(
    name = "control_test",
    size = "small",
    srcs = ["control_test.cpp"],
    copts = COPTS,
    data = glob(["models/*.xml"]) + [
        "reference/mujoco_control.csv",
        "reference/mujoco_feedback.csv",
    ],
    deps = [
        ":robotic_library",
        "@lib//base:testing",
    ],
)

cc_test(
    name = "collision_test",
    size = "small",
    srcs = ["collision_test.cpp"],
    copts = COPTS,
    data = glob(["models/*.xml"]) + ["reference/mujoco_contacts.csv"],
    deps = [
        ":robotic_library",
        "@lib//base:testing",
    ],
)

cc_test(
    name = "constraint_test",
    size = "small",
    srcs = ["constraint_test.cpp"],
    copts = COPTS,
    data = glob(["models/*.xml"]) + [
        "reference/mujoco_constraints.csv",
        "//3rd_party:mujoco",
    ],
    deps = [
        ":robotic_library",
        "@lib//base:testing",
    ],
)
