# Copyright 2022 -- CONTRIBUTORS. See LICENSE.

load("@lib//bazel:copts.bzl", "COPTS")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "event_queue",
    hdrs = ["event_queue.hpp"],
    copts = COPTS,
    deps = ["//core"],
)

cc_test(
    name = "event_queue_test",
    size = "small",
    srcs = ["event_queue_test.cpp"],
    copts = COPTS,
    deps = [
        ":event_queue",
        "@lib//base:testing",
    ],
)
