# Copyright 2026 -- CONTRIBUTORS. See LICENSE.

load("@lib//bazel:copts.bzl", "COPTS")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "vocabulary",
    hdrs = ["vocabulary.hpp"],
    copts = COPTS,
    deps = [
        "//3rd_party:eigen",
        "@lib//base:core",
    ],
)

cc_library(
    name = "framework",
    srcs = [
        "build_error.cpp",
        "name.cpp",
        "spatial_index.cpp",
    ],
    hdrs = [
        "archetype.hpp",
        "build_error.hpp",
        "entity_builder.hpp",
        "command.hpp",
        "entity.hpp",
        "name.hpp",
        "query_builder.hpp",
        "spatial.hpp",
        "spatial_index.hpp",
        "step.hpp",
        "component_store.hpp",
        "system.hpp",
        "type_list.hpp",
        "world.hpp",
        "world_builder.hpp",
    ],
    copts = COPTS,
    deps = [
        ":vocabulary",
        "@lib//base:core",
        "@lib//base:status",
        "@lib//base:time",
    ],
)

cc_library(
    name = "continuous",
    hdrs = ["continuous.hpp"],
    copts = COPTS,
    deps = [
        ":vocabulary",
        ":framework",
        "@lib//base:core",
    ],
)

cc_test(
    name = "continuous_test",
    size = "small",
    srcs = ["continuous_test.cpp"],
    copts = COPTS,
    deps = [
        ":vocabulary",
        ":continuous",
        ":framework",
        "@lib//base:testing",
    ],
)

[cc_test(
    name = test + "_test",
    size = "small",
    srcs = [
        test + "_test.cpp",
        "test_world.hpp",
    ],
    copts = COPTS,
    deps = [
        ":vocabulary",
        ":framework",
        "@lib//base:testing",
    ],
) for test in [
    "entity",
    "name",
    "spatial_index",
    "component_store",
    "system",
    "world",
]]

load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

cc_binary(
    name = "component_store_benchmark",
    srcs = ["component_store_benchmark.cpp"],
    copts = COPTS,
    deps = [
        ":vocabulary",":framework"],
)

cc_binary(
    name = "system_benchmark",
    srcs = ["system_benchmark.cpp"],
    copts = COPTS,
    deps = [
        ":vocabulary",
        ":benchmarking",
        ":framework",
    ],
)

cc_binary(
    name = "churn_benchmark",
    srcs = ["churn_benchmark.cpp"],
    copts = COPTS,
    deps = [
        ":vocabulary",
        ":benchmarking",
        ":framework",
    ],
)

cc_library(
    name = "benchmarking",
    srcs = ["benchmarking.cpp"],
    hdrs = ["benchmarking.hpp"],
    copts = COPTS,
    # For benchmarks only.
    visibility = [
        "//application:__subpackages__",
        "//framework:__pkg__",
    ],
    deps = ["@lib//base:core"],
)

cc_test(
    name = "benchmarking_test",
    size = "small",
    srcs = ["benchmarking_test.cpp"],
    copts = COPTS,
    deps = [
        ":benchmarking",
        "@lib//base:testing",
    ],
)
