# Copyright 2022 -- CONTRIBUTORS. See LICENSE.

load("@lib//bazel:copts.bzl", "COPTS")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
  name = "identity",
  srcs= ["identity.cpp"],
  hdrs= ["identity.hpp"],
  deps = [
    "@lib//base:core",
  ],
  copts = COPTS,
)

cc_test(
  name = "identity_test",
  size = "small",
  srcs = ["identity_test.cpp"],
  deps = [
    "@lib//base:testing",
    ":identity",
  ],
  copts = COPTS,
)

cc_library(
  name = "entity",
  hdrs= ["entity.hpp"],
  deps = [
    ":identity",
    ":component",
  ],
  copts = COPTS,
)

cc_test(
  name = "entity_test",
  size = "small",
  srcs = ["entity_test.cpp"],
  deps = [
    "@lib//base:testing",
    ":entity",
  ],
  copts = COPTS,
)

cc_library(
  name = "event",
  hdrs= ["event.hpp"],
  deps = [
    "@lib//base:time",
    ":identity",
  ],
  copts = COPTS,
)

cc_test(
  name = "event_test",
  size = "small",
  srcs = ["event_test.cpp"],
  deps = [
    "@lib//base:testing",
    ":event",
  ],
  copts = COPTS,
)

cc_library(
  name = "event_queue",
  hdrs= ["event_queue.hpp"],
  deps = [
    "@lib//base:time",
    ":event",
  ],
  copts = COPTS,
)

cc_test(
  name = "event_queue_test",
  size = "small",
  srcs = ["event_queue_test.cpp"],
  deps = [
    "@lib//base:testing",
    ":event_queue",
  ],
  copts = COPTS,
)

cc_library(
  name = "component",
  hdrs= ["component.hpp"],
  deps = [
    ":identity",
  ],
  copts = COPTS,
)

cc_test(
  name = "component_test",
  size = "small",
  srcs = ["component_test.cpp"],
  deps = [
    "@lib//base:testing",
    ":component",
  ],
  copts = COPTS,
)

cc_library(
  name = "component_system",
  hdrs= ["component_system.hpp"],
  deps = [
    "@lib//base:time",
    ":entity",
    ":component",
  ],
  copts = COPTS,
)

cc_test(
  name = "component_system_test",
  size = "small",
  srcs = ["component_system_test.cpp"],
  deps = [
    "@lib//base:testing",
    ":component_system",
  ],
  copts = COPTS,
)

