# Copyright 2026 -- CONTRIBUTORS. See LICENSE.

load("@lib//bazel:copts.bzl", "COPTS")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "openscenario",
    srcs = ["openscenario.cpp"],
    hdrs = ["openscenario.hpp"],
    copts = COPTS,
)

cc_library(
    name = "storyboard",
    srcs = ["storyboard.cpp"],
    hdrs = ["storyboard.hpp"],
    copts = COPTS,
    deps = [
        ":openscenario",
        "//model:road",
        "//model:road_placement",
        "//model:units",
    ],
)

cc_library(
    name = "transition",
    hdrs = ["transition.hpp"],
    copts = COPTS,
    deps = [":openscenario"],
)

cc_library(
    name = "parameter_distribution",
    srcs = ["parameter_distribution.cpp"],
    hdrs = ["parameter_distribution.hpp"],
    copts = COPTS,
)
