# Copyright 2026 -- CONTRIBUTORS. See LICENSE.

load("@lib//bazel:copts.bzl", "COPTS")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "openscenario",
    srcs = ["openscenario.cpp"],
    hdrs = ["openscenario.hpp"],
    copts = COPTS,
)

cc_library(
    name = "storyboard",
    srcs = ["storyboard.cpp"],
    hdrs = ["storyboard.hpp"],
    copts = COPTS,
    deps = [
        "//core:text",
        ":openscenario",
        "//model/road:road",
        "//model/road:placement",
        "//core:units",
    ],
)

cc_library(
    name = "transition",
    hdrs = ["transition.hpp"],
    copts = COPTS,
    deps = [":openscenario"],
)

cc_library(
    name = "parameter_distribution",
    srcs = ["parameter_distribution.cpp"],
    hdrs = ["parameter_distribution.hpp"],
    copts = COPTS,
)

cc_test(
    name = "parameter_distribution_test",
    size = "small",
    srcs = ["parameter_distribution_test.cpp"],
    copts = COPTS,
    data = ["//3rd_party:esmini"],
    deps = [
        ":parameter_distribution",
        "//format:openscenario",
        "@lib//base:testing",
    ],
)

cc_test(
    name = "storyboard_test",
    size = "small",
    srcs = ["storyboard_test.cpp"],
    copts = COPTS,
    deps = [
        ":storyboard",
        "//format:openscenario",
        "//model/road:road",
        "@lib//base:testing",
    ],
)

cc_test(
    name = "transition_test",
    size = "small",
    srcs = ["transition_test.cpp"],
    copts = COPTS,
    deps = [
        ":openscenario",
        ":transition",
        "@lib//base:testing",
    ],
)
