#include "status.hpp"

#include <cstring>

namespace simon {

bool PosixStatusDomain::has_equivalent_condition_of(
    Status status, Status other) const noexcept {
  return false;
}

bool PosixStatusDomain::has_equivalent_condition_of(
    Status status, StatusKind kind) const noexcept {
  return false;
}

bool Win32StatusDomain::has_equivalent_condition_of(
    Status status, Status other) const noexcept {
  return false;
}

bool Win32StatusDomain::has_equivalent_condition_of(
    Status status, StatusKind kind) const noexcept {
  return false;
}

template <>
const std::array<StatusConditionEntry, impl::POSIX_CONDITION_COUNT>
    EnumStatusDomain<PosixCondition, impl::POSIX_CONDITION_COUNT>::conditions_ =
        {
            StatusConditionEntry{"Argument list too long."},
            StatusConditionEntry{"Permission denied."},
            StatusConditionEntry{"Address in use."},
            StatusConditionEntry{"Address not available."},
            StatusConditionEntry{"Address family not supported."},
            StatusConditionEntry{"Resource unavailable}, try again."},
            StatusConditionEntry{"Connection already in progress."},
            StatusConditionEntry{"Bad file descriptor."},
            StatusConditionEntry{"Bad message."},
            StatusConditionEntry{"Device or resource busy."},
            StatusConditionEntry{"Operation canceled."},
            StatusConditionEntry{"No child processes."},
            StatusConditionEntry{"Connection aborted."},
            StatusConditionEntry{"Connection refused."},
            StatusConditionEntry{"Connection reset."},
            StatusConditionEntry{"Resource deadlock would occur."},
            StatusConditionEntry{"Destination address required."},
            StatusConditionEntry{
                "Mathematics argument out of domain of function."},
            StatusConditionEntry{"Reserved."},  //
            StatusConditionEntry{"File exists."},
            StatusConditionEntry{"Bad address."},
            StatusConditionEntry{"File too large."},
            StatusConditionEntry{"Host is unreachable."},
            StatusConditionEntry{"Identifier removed."},
            StatusConditionEntry{"Illegal byte sequence."},
            StatusConditionEntry{"Operation in progress."},
            StatusConditionEntry{"Interrupted function."},
            StatusConditionEntry{"Invalid argument."},
            StatusConditionEntry{"I/O error."},
            StatusConditionEntry{"Socket is connected."},
            StatusConditionEntry{"Is a directory."},
            StatusConditionEntry{"Too many levels of symbolic links."},
            StatusConditionEntry{"File descriptor value too large."},
            StatusConditionEntry{"Too many links."},
            StatusConditionEntry{"Message too large."},
            StatusConditionEntry{"Reserved."},
            StatusConditionEntry{"Filename too long."},
            StatusConditionEntry{"Network is down."},
            StatusConditionEntry{"Connection aborted by network."},
            StatusConditionEntry{"Network unreachable."},
            StatusConditionEntry{"Too many files open in system."},
            StatusConditionEntry{"No buffer space available."},
            StatusConditionEntry{
                "No message is available on the STREAM head read queue."},
            StatusConditionEntry{"No such device."},
            StatusConditionEntry{"No such file or directory."},
            StatusConditionEntry{"Executable file format error."},
            StatusConditionEntry{"No locks available."},
            StatusConditionEntry{"Reserved."},
            StatusConditionEntry{"Not enough space."},
            StatusConditionEntry{"No message of the desired type."},
            StatusConditionEntry{"Protocol not available."},
            StatusConditionEntry{"No space left on device."},
            StatusConditionEntry{"No STREAM resources."},
            StatusConditionEntry{"Not a STREAM. "},
            StatusConditionEntry{"Functionality not supported."},
            StatusConditionEntry{"The socket is not connected."},
            StatusConditionEntry{
                "Not a directory or a symbolic link to a directory."},
            StatusConditionEntry{"Directory not empty."},
            StatusConditionEntry{"State not recoverable."},
            StatusConditionEntry{"Not a socket."},
            StatusConditionEntry{"Not supported."},
            StatusConditionEntry{"Inappropriate I/O control operation."},
            StatusConditionEntry{"No such device or address."},
            StatusConditionEntry{"Operation not supported on socket."},
            StatusConditionEntry{"Value too large to be stored in data type."},
            StatusConditionEntry{"Previous owner died."},
            StatusConditionEntry{"Operation not permitted."},
            StatusConditionEntry{"Broken pipe."},
            StatusConditionEntry{"Protocol error."},
            StatusConditionEntry{"Protocol not supported."},
            StatusConditionEntry{"Protocol wrong type for socket."},
            StatusConditionEntry{"Result too large."},
            StatusConditionEntry{"Read-only file system."},
            StatusConditionEntry{"Invalid seek."},
            StatusConditionEntry{"No such process."},
            StatusConditionEntry{"Reserved."},
            StatusConditionEntry{"Stream ioctl() timeout."},
            StatusConditionEntry{"Connection timed out."},
            StatusConditionEntry{"Text file busy."},
            StatusConditionEntry{"Operation would block."},
            StatusConditionEntry{"Cross-device link."},
};

template <>
const std::array<StatusConditionEntry, impl::WIN32_CONDITION_COUNT>
    EnumStatusDomain<Win32Condition, impl::WIN32_CONDITION_COUNT>::conditions_ =
        {
            StatusConditionEntry{"ERROR_INVALID_FUNCTION"},
            StatusConditionEntry{"ERROR_FILE_NOT_FOUND"},
            StatusConditionEntry{"ERROR_PATH_NOT_FOUND"},
            StatusConditionEntry{"ERROR_TOO_MANY_OPEN_FILES"},
            StatusConditionEntry{"ERROR_ACCESS_DENIED"},
            StatusConditionEntry{"ERROR_INVALID_HANDLE"},
            StatusConditionEntry{"ERROR_ARENA_TRASHED"},
            StatusConditionEntry{"ERROR_NOT_ENOUGH_MEMORY"},
            StatusConditionEntry{"ERROR_INVALID_BLOCK"},
            StatusConditionEntry{"ERROR_BAD_ENVIRONMENT"},
            StatusConditionEntry{"ERROR_BAD_FORMAT"},
            StatusConditionEntry{"ERROR_INVALID_ACCESS"},
            StatusConditionEntry{"ERROR_INVALID_DATA"},
            StatusConditionEntry{"ERROR_OUTOFMEMORY"},
            StatusConditionEntry{"ERROR_INVALID_DRIVE"},
            StatusConditionEntry{"ERROR_CURRENT_DIRECTORY"},
            StatusConditionEntry{"ERROR_NOT_SAME_DEVICE"},
            StatusConditionEntry{"ERROR_NO_MORE_FILES"},
            StatusConditionEntry{"ERROR_WRITE_PROTECT"},
            StatusConditionEntry{"ERROR_BAD_UNIT"},
            StatusConditionEntry{"ERROR_NOT_READY"},
            StatusConditionEntry{"ERROR_BAD_COMMAND"},
            StatusConditionEntry{"ERROR_CRC"},
            StatusConditionEntry{"ERROR_BAD_LENGTH"},
            StatusConditionEntry{"ERROR_SEEK"},
            StatusConditionEntry{"ERROR_NOT_DOS_DISK"},
            StatusConditionEntry{"ERROR_SECTOR_NOT_FOUND"},
            StatusConditionEntry{"ERROR_OUT_OF_PAPER"},
            StatusConditionEntry{"ERROR_WRITE_FAULT"},
            StatusConditionEntry{"ERROR_READ_FAULT"},
            StatusConditionEntry{"ERROR_GEN_FAILURE"},
            StatusConditionEntry{"ERROR_SHARING_VIOLATION"},
            StatusConditionEntry{"ERROR_LOCK_VIOLATION"},
            StatusConditionEntry{"ERROR_WRONG_DISK"},
            StatusConditionEntry{"ERROR_SHARING_BUFFER_EXCEEDED"},
            StatusConditionEntry{"ERROR_HANDLE_EOF"},
            StatusConditionEntry{"ERROR_HANDLE_DISK_FULL"},
            StatusConditionEntry{"ERROR_NOT_SUPPORTED"},
            StatusConditionEntry{"ERROR_REM_NOT_LIST"},
            StatusConditionEntry{"ERROR_DUP_NAME"},
            StatusConditionEntry{"ERROR_BAD_NETPATH"},
            StatusConditionEntry{"ERROR_NETWORK_BUSY"},
            StatusConditionEntry{"ERROR_DEV_NOT_EXIST"},
            StatusConditionEntry{"ERROR_TOO_MANY_CMDS"},
            StatusConditionEntry{"ERROR_ADAP_HDW_ERR"},
            StatusConditionEntry{"ERROR_BAD_NET_RESP"},
            StatusConditionEntry{"ERROR_UNEXP_NET_ERR"},
            StatusConditionEntry{"ERROR_BAD_REM_ADAP"},
            StatusConditionEntry{"ERROR_PRINTQ_FULL"},
            StatusConditionEntry{"ERROR_NO_SPOOL_SPACE"},
            StatusConditionEntry{"ERROR_PRINT_CANCELED"},
            StatusConditionEntry{"ERROR_NETNAME_DELETED"},
            StatusConditionEntry{"ERROR_NETWORK_ACCESS_DENIED"},
            StatusConditionEntry{"ERROR_BAD_DEV_TYPE"},
            StatusConditionEntry{"ERROR_BAD_NET_NAME"},
            StatusConditionEntry{"ERROR_TOO_MANY_NAMES"},
            StatusConditionEntry{"ERROR_TOO_MANY_SESS"},
            StatusConditionEntry{"ERROR_SHARING_PAUSED"},
            StatusConditionEntry{"ERROR_REQ_NOT_ACCEP"},
            StatusConditionEntry{"ERROR_REDIR_PAUSED"},
            StatusConditionEntry{"ERROR_FILE_EXISTS"},
            StatusConditionEntry{"ERROR_CANNOT_MAKE"},
            StatusConditionEntry{"ERROR_FAIL_I24"},
            StatusConditionEntry{"ERROR_OUT_OF_STRUCTURES"},
            StatusConditionEntry{"ERROR_ALREADY_ASSIGNED"},
            StatusConditionEntry{"ERROR_INVALID_PASSWORD"},
            StatusConditionEntry{"ERROR_INVALID_PARAMETER"},
            StatusConditionEntry{"ERROR_NET_WRITE_FAULT"},
            StatusConditionEntry{"ERROR_NO_PROC_SLOTS"},
            StatusConditionEntry{"ERROR_TOO_MANY_SEMAPHORES"},
            StatusConditionEntry{"ERROR_EXCL_SEM_ALREADY_OWNED"},
            StatusConditionEntry{"ERROR_SEM_IS_SET"},
            StatusConditionEntry{"ERROR_TOO_MANY_SEM_REQUESTS"},
            StatusConditionEntry{"ERROR_INVALID_AT_INTERRUPT_TIME"},
            StatusConditionEntry{"ERROR_SEM_OWNER_DIED"},
            StatusConditionEntry{"ERROR_SEM_USER_LIMIT"},
            StatusConditionEntry{"ERROR_DISK_CHANGE"},
            StatusConditionEntry{"ERROR_DRIVE_LOCKED"},
            StatusConditionEntry{"ERROR_BROKEN_PIPE"},
            StatusConditionEntry{"ERROR_OPEN_FAILED"},
            StatusConditionEntry{"ERROR_BUFFER_OVERFLOW"},
            StatusConditionEntry{"ERROR_DISK_FULL"},
            StatusConditionEntry{"ERROR_NO_MORE_SEARCH_HANDLES"},
            StatusConditionEntry{"ERROR_INVALID_TARGET_HANDLE"},
            StatusConditionEntry{"ERROR_INVALID_CATEGORY"},
            StatusConditionEntry{"ERROR_INVALID_VERIFY_SWITCH"},
            StatusConditionEntry{"ERROR_BAD_DRIVER_LEVEL"},
            StatusConditionEntry{"ERROR_CALL_NOT_IMPLEMENTED"},
            StatusConditionEntry{"ERROR_SEM_TIMEOUT"},
            StatusConditionEntry{"ERROR_INSUFFICIENT_BUFFER"},
            StatusConditionEntry{"ERROR_INVALID_NAME"},
            StatusConditionEntry{"ERROR_INVALID_LEVEL"},
            StatusConditionEntry{"ERROR_NO_VOLUME_LABEL"},
            StatusConditionEntry{"ERROR_MOD_NOT_FOUND"},
            StatusConditionEntry{"ERROR_PROC_NOT_FOUND"},
            StatusConditionEntry{"ERROR_WAIT_NO_CHILDREN"},
            StatusConditionEntry{"ERROR_CHILD_NOT_COMPLETE"},
            StatusConditionEntry{"ERROR_DIRECT_ACCESS_HANDLE"},
            StatusConditionEntry{"ERROR_NEGATIVE_SEEK"},
            StatusConditionEntry{"ERROR_SEEK_ON_DEVICE"},
            StatusConditionEntry{"ERROR_IS_JOIN_TARGET"},
            StatusConditionEntry{"ERROR_IS_JOINED"},
            StatusConditionEntry{"ERROR_IS_SUBSTED"},
            StatusConditionEntry{"ERROR_NOT_JOINED"},
            StatusConditionEntry{"ERROR_NOT_SUBSTED"},
            StatusConditionEntry{"ERROR_JOIN_TO_JOIN"},
            StatusConditionEntry{"ERROR_SUBST_TO_SUBST"},
            StatusConditionEntry{"ERROR_JOIN_TO_SUBST"},
            StatusConditionEntry{"ERROR_SUBST_TO_JOIN"},
            StatusConditionEntry{"ERROR_BUSY_DRIVE"},
            StatusConditionEntry{"ERROR_SAME_DRIVE"},
            StatusConditionEntry{"ERROR_DIR_NOT_ROOT"},
            StatusConditionEntry{"ERROR_DIR_NOT_EMPTY"},
            StatusConditionEntry{"ERROR_IS_SUBST_PATH"},
            StatusConditionEntry{"ERROR_IS_JOIN_PATH"},
            StatusConditionEntry{"ERROR_PATH_BUSY"},
            StatusConditionEntry{"ERROR_IS_SUBST_TARGET"},
            StatusConditionEntry{"ERROR_SYSTEM_TRACE"},
            StatusConditionEntry{"ERROR_INVALID_EVENT_COUNT"},
            StatusConditionEntry{"ERROR_TOO_MANY_MUXWAITERS"},
            StatusConditionEntry{"ERROR_INVALID_LIST_FORMAT"},
            StatusConditionEntry{"ERROR_LABEL_TOO_LONG"},
            StatusConditionEntry{"ERROR_TOO_MANY_TCBS"},
            StatusConditionEntry{"ERROR_SIGNAL_REFUSED"},
            StatusConditionEntry{"ERROR_DISCARDED"},
            StatusConditionEntry{"ERROR_NOT_LOCKED"},
            StatusConditionEntry{"ERROR_BAD_THREADID_ADDR"},
            StatusConditionEntry{"ERROR_BAD_ARGUMENTS"},
            StatusConditionEntry{"ERROR_BAD_PATHNAME"},
            StatusConditionEntry{"ERROR_SIGNAL_PENDING"},
            StatusConditionEntry{"ERROR_MAX_THRDS_REACHED"},
            StatusConditionEntry{"ERROR_LOCK_FAILED"},
            StatusConditionEntry{"ERROR_BUSY"},
            StatusConditionEntry{"ERROR_CANCEL_VIOLATION"},
            StatusConditionEntry{"ERROR_ATOMIC_LOCKS_NOT_SUPPORTED"},
            StatusConditionEntry{"ERROR_INVALID_SEGMENT_NUMBER"},
            StatusConditionEntry{"ERROR_INVALID_ORDINAL"},
            StatusConditionEntry{"ERROR_ALREADY_EXISTS"},
            StatusConditionEntry{"ERROR_INVALID_FLAG_NUMBER"},
            StatusConditionEntry{"ERROR_SEM_NOT_FOUND"},
            StatusConditionEntry{"ERROR_INVALID_STARTING_CODESEG"},
            StatusConditionEntry{"ERROR_INVALID_STACKSEG"},
            StatusConditionEntry{"ERROR_INVALID_MODULETYPE"},
            StatusConditionEntry{"ERROR_INVALID_EXE_SIGNATURE"},
            StatusConditionEntry{"ERROR_EXE_MARKED_INVALID"},
            StatusConditionEntry{"ERROR_BAD_EXE_FORMAT"},
            StatusConditionEntry{"ERROR_ITERATED_DATA_EXCEEDS_64k"},
            StatusConditionEntry{"ERROR_INVALID_MINALLOCSIZE"},
            StatusConditionEntry{"ERROR_DYNLINK_FROM_INVALID_RING"},
            StatusConditionEntry{"ERROR_IOPL_NOT_ENABLED"},
            StatusConditionEntry{"ERROR_INVALID_SEGDPL"},
            StatusConditionEntry{"ERROR_AUTODATASEG_EXCEEDS_64k"},
            StatusConditionEntry{"ERROR_RING2SEG_MUST_BE_MOVABLE"},
            StatusConditionEntry{"ERROR_RELOC_CHAIN_XEEDS_SEGLIM"},
            StatusConditionEntry{"ERROR_INFLOOP_IN_RELOC_CHAIN"},
            StatusConditionEntry{"ERROR_ENVVAR_NOT_FOUND"},
            StatusConditionEntry{"ERROR_NO_SIGNAL_SENT"},
            StatusConditionEntry{"ERROR_FILENAME_EXCED_RANGE"},
            StatusConditionEntry{"ERROR_RING2_STACK_IN_USE"},
            StatusConditionEntry{"ERROR_META_EXPANSION_TOO_LONG"},
            StatusConditionEntry{"ERROR_INVALID_SIGNAL_NUMBER"},
            StatusConditionEntry{"ERROR_THREAD_1_INACTIVE"},
            StatusConditionEntry{"ERROR_LOCKED"},
            StatusConditionEntry{"ERROR_TOO_MANY_MODULES"},
            StatusConditionEntry{"ERROR_NESTING_NOT_ALLOWED"},
            StatusConditionEntry{"ERROR_EXE_MACHINE_TYPE_MISMATCH"},
            StatusConditionEntry{"ERROR_BAD_PIPE"},
            StatusConditionEntry{"ERROR_PIPE_BUSY"},
            StatusConditionEntry{"ERROR_NO_DATA"},
            StatusConditionEntry{"ERROR_PIPE_NOT_CONNECTED"},
            StatusConditionEntry{"ERROR_MORE_DATA"},
            StatusConditionEntry{"ERROR_VC_DISCONNECTED"},
            StatusConditionEntry{"ERROR_INVALID_EA_NAME"},
            StatusConditionEntry{"ERROR_EA_LIST_INCONSISTENT"},
            StatusConditionEntry{"WAIT_TIMEOUT"},
            StatusConditionEntry{"ERROR_NO_MORE_ITEMS"},
            StatusConditionEntry{"ERROR_CANNOT_COPY"},
            StatusConditionEntry{"ERROR_DIRECTORY"},
            StatusConditionEntry{"ERROR_EAS_DIDNT_FIT"},
            StatusConditionEntry{"ERROR_EA_FILE_CORRUPT"},
            StatusConditionEntry{"ERROR_EA_TABLE_FULL"},
            StatusConditionEntry{"ERROR_INVALID_EA_HANDLE"},
            StatusConditionEntry{"ERROR_EAS_NOT_SUPPORTED"},
            StatusConditionEntry{"ERROR_NOT_OWNER"},
            StatusConditionEntry{"ERROR_TOO_MANY_POSTS"},
            StatusConditionEntry{"ERROR_PARTIAL_COPY"},
            StatusConditionEntry{"ERROR_OPLOCK_NOT_GRANTED"},
            StatusConditionEntry{"ERROR_INVALID_OPLOCK_PROTOCOL"},
            StatusConditionEntry{"ERROR_MR_MID_NOT_FOUND"},
            StatusConditionEntry{"ERROR_INVALID_ADDRESS"},
            StatusConditionEntry{"ERROR_ARITHMETIC_OVERFLOW"},
            StatusConditionEntry{"ERROR_PIPE_CONNECTED"},
            StatusConditionEntry{"ERROR_PIPE_LISTENING"},
            StatusConditionEntry{"ERROR_EA_ACCESS_DENIED"},
            StatusConditionEntry{"ERROR_OPERATION_ABORTED"},
            StatusConditionEntry{"ERROR_IO_INCOMPLETE"},
            StatusConditionEntry{"ERROR_IO_PENDING"},
            StatusConditionEntry{"ERROR_NOACCESS"},
            StatusConditionEntry{"ERROR_SWAPERROR"},
};

}  // namespace simon
