# Copyright 2026 -- CONTRIBUTORS. See LICENSE.

load("@lib//bazel:copts.bzl", "COPTS")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "right_of_way",
    srcs = ["right_of_way.cpp"],
    hdrs = ["right_of_way.hpp"],
    copts = COPTS,
    deps = [
        "//model/road:lane_graph",
        "//model/road:road",
        ":signals",
        "//core:units",
    ],
)


cc_library(
    name = "signals",
    srcs = ["signals.cpp"],
    hdrs = ["signals.hpp"],
    copts = COPTS,
    deps = [
        "//model/road:lane_graph",
        "//model/road:road",
        ":traffic",
        "//core:units",
        "@lib//base:core",
    ],
)


cc_library(
    name = "traffic",
    hdrs = ["traffic.hpp"],
    copts = COPTS,
    deps = ["//core:units"],
)


cc_library(
    name = "driving_metrics",
    srcs = ["driving_metrics.cpp"],
    hdrs = ["driving_metrics.hpp"],
    copts = COPTS,
    deps = ["//model:collision"],
)


[cc_test(
    name = test + "_test",
    size = "small",
    srcs = [test + "_test.cpp"],
    copts = COPTS,
    deps = [
        ":" + test,
        "@lib//base:testing",
    ],
) for test in [
    "signals",
]]
