load("//src:copts.bzl", "COPTS")

cc_binary(
    name = "hello",
    srcs = ["hello.cpp"],
    copts = COPTS,
)

# cc_test(
#     name = "hello_test",
#     srcs = ["hello_test.cpp"],
#     copts = COPTS,
#     defines = ["CATCH_CONFIG_MAIN"],
#     deps = [
#         "@catch2//:catch2",
#     ],
# )
