# Copyright 2022 -- CONTRIBUTORS. See LICENSE.

load("@lib//bazel:copts.bzl", "COPTS")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
  name = "controls",
  hdrs= ["controls.hpp"],
  deps = [
    "@lib//base:math",
    "//framework:component",
  ],
  copts = COPTS,
)

cc_test(
  name = "controls_test",
  size = "small",
  srcs = ["controls_test.cpp"],
  deps = [
    "@lib//base:testing",
    ":controls",
  ],
  copts = COPTS,
)

cc_library(
  name = "environment",
  hdrs= ["environment.hpp"],
  deps = [
    "@lib//base:math",
    "//framework:component",
  ],
  copts = COPTS,
)

cc_test(
  name = "environment_test",
  size = "small",
  srcs = ["environment_test.cpp"],
  deps = [
    "@lib//base:testing",
    ":environment",
  ],
  copts = COPTS,
)

cc_library(
  name = "movement",
  hdrs= ["movement.hpp"],
  deps = [
    "@lib//base:math",
    "//framework:component",
  ],
  copts = COPTS,
)

cc_test(
  name = "movement_test",
  size = "small",
  srcs = ["movement_test.cpp"],
  deps = [
    "@lib//base:testing",
    ":movement",
  ],
  copts = COPTS,
)

cc_library(
  name = "physical",
  hdrs= ["physical.hpp"],
  deps = [
    "@lib//base:math",
    "//framework:component",
  ],
  copts = COPTS,
)

cc_test(
  name = "physical_test",
  size = "small",
  srcs = ["physical_test.cpp"],
  deps = [
    "@lib//base:testing",
    ":physical",
  ],
  copts = COPTS,
)

